spring:
  application:
    name: apiGateway
  cloud:
    gateway:
      routes:
        - id: eureka-client
          uri: lb://EUREKA-CLIENT
          predicates:
            - Path=/main/test
            - Method=GET
        - id: eureka-client-2
          uri: lb://EUREKA-CLIENT-2
          predicates:
            - Path=/main2/test
            - Method=GET
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
server:
  port: 8765

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    com:
      netflix:
        eureka: trace
        discovery: trace


