spring:
  application:
    name: eureka-client-2
server:
  port: 0
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
#logging:
#  level:
#    com:
#      netflix:
#        eureka: error
#        discovery: error
#  pattern:
#    console: %{1.} [%-5level] %d{HH:mm:ss} - %msg%n
